# Generated by Django 3.1.12 on 2025-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.EmailField(help_text='user_email', max_length=254, unique=True)),
                ('user_password', models.EmailField(help_text='user_password', max_length=50)),
                ('user_address', models.TextField(help_text='user_address', max_length=100)),
                ('user_contact', models.CharField(help_text='user_contact', max_length=15, null=True)),
                ('age', models.CharField(help_text='age', max_length=3, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('Otp_Num', models.IntegerField(null=True)),
                ('Otp_Status', models.TextField(default='pending', max_length=60, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
