# Generated by Django 3.1.12 on 2025-09-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Review', models.CharField(max_length=225, null=True)),
                ('Sentiment', models.CharField(max_length=100, null=True)),
                ('Reviewer', models.EmailField(help_text='user_email', max_length=254)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
