# Generated by Django 3.1.12 on 2025-09-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenseNetModel',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('model_accuracy', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=10)),
                ('model_executed', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'DenseNet_model',
            },
        ),
        migrations.CreateModel(
            name='InceptionModel',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('model_accuracy', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=20)),
                ('model_executed', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Inception_model',
            },
        ),
        migrations.CreateModel(
            name='MobileNetModel',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('model_accuracy', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=10)),
                ('model_executed', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'MobileNet_model',
            },
        ),
    ]
