# Generated by Django 3.1.12 on 2025-10-09 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_result', models.CharField(default='Unknown', max_length=100)),
                ('model_accuracy', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_email', models.EmailField(help_text='user_email', max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Prediction_Record',
            },
        ),
    ]
