# Generated by Django 3.1.12 on 2025-10-10 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_predictionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('posted_by', models.EmailField(max_length=254)),
                ('answers', djongo.models.fields.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Comm_Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answered_by', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.question')),
            ],
            options={
                'db_table': 'Comm_Answers',
            },
        ),
    ]
