# Generated by Django 3.1.12 on 2025-10-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sentiment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
